// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ9ns_8gErhKtIlVRTW7ZDUuOVKoS6iTc',
    appId: '1:99046813039:web:c1f02aab17f2be80f84c9a',
    messagingSenderId: '99046813039',
    projectId: 'csc-fridge',
    authDomain: 'csc-fridge.firebaseapp.com',
    storageBucket: 'csc-fridge.firebasestorage.app',
    measurementId: 'G-JR4ZPKX7J5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsiOxrbgl8bfpmaffrRyqzY6zb3olW5RU',
    appId: '1:99046813039:android:ca35e368bdc21eb7f84c9a',
    messagingSenderId: '99046813039',
    projectId: 'csc-fridge',
    storageBucket: 'csc-fridge.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA142LlLN-0ObCI_yQrZnu-fIyyhxk-DMg',
    appId: '1:99046813039:ios:a9625f787d966b67f84c9a',
    messagingSenderId: '99046813039',
    projectId: 'csc-fridge',
    storageBucket: 'csc-fridge.firebasestorage.app',
    iosBundleId: 'com.example.fridge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA142LlLN-0ObCI_yQrZnu-fIyyhxk-DMg',
    appId: '1:99046813039:ios:a9625f787d966b67f84c9a',
    messagingSenderId: '99046813039',
    projectId: 'csc-fridge',
    storageBucket: 'csc-fridge.firebasestorage.app',
    iosBundleId: 'com.example.fridge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJ9ns_8gErhKtIlVRTW7ZDUuOVKoS6iTc',
    appId: '1:99046813039:web:fac997f26714f9d1f84c9a',
    messagingSenderId: '99046813039',
    projectId: 'csc-fridge',
    authDomain: 'csc-fridge.firebaseapp.com',
    storageBucket: 'csc-fridge.firebasestorage.app',
    measurementId: 'G-GEJ1912TBW',
  );
}
